# -*- coding: utf-8 -*-
"""Lab 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Docbn_kB5tt9BrP3RF8SfQ2rX1cgDmLG
"""

print("----------Question 1----------")
#SET maxNum to list[0]
#SET i to 1
#FOR i to length.list – 1
  #IF list[i] > maxNumber
#THEN
	#SET maxNumber to list[i]
#ENDIF
#ENDFOR
#PRINT maxNum

print("----------Question 2----------")
import random 

def create_list(MAX_LEN, my_list):
  for i in range(MAX_LEN):
    my_list.append(random.randint(1,99))
  print(my_list)

create_list(MAX_LEN = int(input("Please enter the max length of the list: ")), my_list=[])

print("----------Question 3----------")
names = ["Jennifer", "Albatross", "Justin", "Dave", "Shankarnarayan", "Ezra", "Alice", "Kwabena"]
count_list = []

for count in names:
  count_list.append(len(count))
print(count_list)

print("----------Question 4----------")
names = ["Jennifer", "Albatross", "Justin", "Dave", "Shankarnarayan", "Ezra", "Alice", "Kwabena"]
count_list = []

for i in names:
  if len(names[0]) >= len(i)-1:
    print("Names shorter in length than Jennifer are ")
    print(i)