# -*- coding: utf-8 -*-
"""Lab 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xUFNZ8lsC2hlH3w5P1N4MFuqx_klov9m
"""



print("Hello World")