# -*- coding: utf-8 -*-
"""Lab 8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NXK4uhFIR3n27eqElfP06uim8oFfPzNU
"""

print("Question 6")
SCORES = [40, 91, 85, 15]

output = [(a,b)for c, a in enumerate(SCORES) for b in SCORES[c + 1:]]

for i in output:
  print(i)

print("Extra Credit")
s = "i_love_programming_in_python_and_i_will_alzways_program"
unique = list(set(s))

print(unique)