# -*- coding: utf-8 -*-
"""Lab 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12BaY4e-iu6NhW-ol2ZgtS3RwiNWGvh7s
"""

#Question 1:
for i in range (10,100):
	print (i)

print ("----------Question 2----------")

#Question 2:
a = int (input ("Enter a number between 0 and 99:"))

if a < 9:
	print ("Single Digit Number")
else: 
	print ("Double Digit Number")

print ("----------Question 3----------")

#Question 3:
for i in range (10, 100, 2):
  print(i)

print ("----------Question 4----------")

#Question 4:
for i in range (5, 55, 5):
  print(i)

print ("----------Question 5----------")

#Question 5:
for i in range (5, 55, 5):
  if i % 3 == 0:
    print(i, "is divisible by 3")
  else:
    print(i)

print ("----------Question 7----------")

#Question 7:
prices = [10, 130, 25, 64, 91, 66, 42, 18, 141, 64]
print(prices)

print ("----------Question 8----------")

#Question 8:
prices = [10,130,25,64,91,66,42,18,141,64]
filtered_list = []

for prices in prices:
  if prices <= 80 and prices >= 20:
    filtered_list.append(prices)

print(filtered_list)

print ("----------Question 9----------")
#Question 9:

username = input("Please enter username: ")
password = input("Please enter the password: ")

if username != "student007" and password != "new_password":
  print("Try again. Login failure")
else:
  print("Login successful")

print ("----------Question 10----------")
#Question 10:

username = input("Please enter username: ")

if len(username) < 5 or len(username) > 16:
  print("Invalid username")
else:
  print("Valid username")