# -*- coding: utf-8 -*-
"""Question 35.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MUTzc-DLCsq0Z6RA2e7UMZUg-kAr84nO
"""

def AND(A,B):
  return A & B

def NOT(A):
  return ~A+2

def NAND(A,B):
  return NOT(AND())