# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUxbgMXL50mRs0QwNCUMhxovBXBmsEI6
"""

import requests

response = requests.get("http://www.nytimes.com")
print(response.status_code)
print(response.headers["Content-Type"])

if response.status_code == 200:
  print("SUCCESS")
else:
  print("Error")